# Generated by Django 4.2 on 2026-05-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(help_text='Unique identifier for the video session', max_length=255, unique=True)),
                ('session_type', models.CharField(choices=[('1v1', 'One-on-One (Private)'), ('group', 'Multi-peer (Group)')], default='group', help_text='Type of video session', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_users', models.ManyToManyField(blank=True, help_text='Users currently in this session', related_name='active_video_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Session',
                'verbose_name_plural': 'Video Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(help_text="User's date of birth (DD/MM/YYYY format)")),
                ('is_banned', models.BooleanField(default=False, help_text='If True, user cannot access video chat features')),
                ('banned_reason', models.TextField(blank=True, help_text='Reason for banning the user', null=True)),
                ('banned_at', models.DateTimeField(blank=True, help_text='Timestamp when user was banned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videosession',
            index=models.Index(fields=['room_id', 'is_active'], name='video_chat__room_id_49532f_idx'),
        ),
        migrations.AddIndex(
            model_name='videosession',
            index=models.Index(fields=['is_active'], name='video_chat__is_acti_1e6264_idx'),
        ),
    ]
